### ISSUE TITLE
Adicionar mais detalhes ao Readme

### ISSUE THREAD

**Issue by JMBeling** [JMBeling2/desafio-github-markdown#1]
Adicione mais detalhes ao readme como:

- Curso
- Professor responsável
- Certificado de conclusão

**Comment by JMBeling** [comment]
Pode adicionar alguma imagem também.

**Comment by JMBeling2** [comment]
Sim, vou adicionar.

**Comment by JMBeling2** [comment]
Finalizei o que pediu
